#!/bin/sh

#https://wiki.archlinux.org/index.php/Xprofile
# Make sure this is before the 'exec' command or it won't be sourced.

#[ -f /etc/xprofile ] && . /etc/xprofile
#[ -f ~/.xprofile ] && . ~/.xprofile
[ -f ~/.config/x11/xprofile ] && . ~/.config/x11/xprofile


#https://github.com/LukeSmithxyz/voidrice/blob/master/.config/x11/xinitrc
# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

#if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
#	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
#else
#	. "$HOME/.xprofile"
#fi

#ssh-agent dwm
exec dwm

